Missing namespace for Decodable
Looks like there was one more un-namespaced mention of Decodable, which (under Xcode 9 Beta 6) was causing an "error: 'Decodable' is ambiguous for type lookup in this context" compilation error. This seems to fix that problem...